community_workspace <- function() {
  override <- Sys.getenv("COMMUNITY_WORKSPACE", unset = "")
  if (nzchar(override)) return(normalizePath(override, mustWork = TRUE))
  script <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (!length(script)) stop("Run with Rscript or set COMMUNITY_WORKSPACE.")
  dirname(normalizePath(sub("^--file=", "", script[[1]]), mustWork = TRUE))
}

# ===========================================================
# plot_mechanism_axes.R
#
# Story-focused mechanism plots:
#   1. Species concentration vs dynamic mode dispersion
#   2. Species concentration vs leave-one-out dependence
#   3. Species concentration vs asynchrony
#
# Each experiment is plotted separately. Conditions are intentionally not
# encoded by shape/color here; color represents cumulative Shannon excess:
# cumulative_shannon - mean_daily_shannon.
#
# Requires:
#   processed/mechanism_axes/mechanism_metrics.csv
# generated by:
#   python calculate_mechanism_axes.py
# ===========================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(ggplot2)
  library(scales)
})

BASE_DIR <- community_workspace()
PROC_DIR <- file.path(BASE_DIR, "processed")
FIG_DIR  <- file.path(BASE_DIR, "figures", "mechanism_axes_story")
DATA_PATH <- file.path(PROC_DIR, "mechanism_axes", "mechanism_metrics.csv")

dir.create(FIG_DIR, showWarnings = FALSE, recursive = TRUE)

if (!file.exists(DATA_PATH)) {
  stop("Missing mechanism_metrics.csv. Run: python calculate_mechanism_axes.py")
}

FONT_FAMILY <- "Arial"
FONT_AX <- 10
FONT_LEGEND <- 8

W_PLOT <- 78
H_PLOT <- 68

POINT_SIZE <- 2.2
POINT_ALPHA <- 0.86
POINT_STROKE <- 0.18
BORDER_SIZE <- 0.25
TICK_SIZE <- 0.20
TICK_LEN <- -0.7

# The eigenvalue-based axes are most interpretable in the longest available
# window. last3 has only three time points, so its covariance matrix is rank
# limited and can exaggerate single-mode structure.
WINDOWS_TO_PLOT <- c("long")
SCOPES_TO_PLOT <- c("all_noncollapsed", "fluctuating_only")

STORY_PAIRS <- tribble(
  ~x, ~y, ~tag,
  "species_ipr_var", "mode_dispersion_corr", "01_concentration_vs_mode_dispersion",
  "species_ipr_var", "leave_one_out_sum_abs_std_max_effect", "02_concentration_vs_species_leave_one_out",
  "species_ipr_var", "asynchrony", "03_concentration_vs_asynchrony"
)

METRIC_GUIDE <- tribble(
  ~metric, ~label, ~lo, ~hi,
  "species_ipr_var", "Species fluctuation concentration (IPR)", 0, 1,
  "mode_dispersion_corr", "Dynamic mode dispersion (1 - rho1)", 0, 1,
  "leave_one_out_sum_abs_std_max_effect", "Species-fluctuation dependence", 0, 1,
  "asynchrony", "Asynchrony (1 - phi)", 0, 1
)

COLOR_LOW <- "#3E6F8E"
COLOR_MID <- "#D8D2B8"
COLOR_HIGH <- "#B8574F"

theme_story <- function() {
  theme_classic(base_size = FONT_AX, base_family = FONT_FAMILY) +
    theme(
      axis.line = element_blank(),
      panel.border = element_rect(linewidth = BORDER_SIZE,
                                  color = "black", fill = NA),
      axis.ticks = element_line(linewidth = TICK_SIZE, color = "black"),
      axis.ticks.length = unit(TICK_LEN, "mm"),
      axis.text = element_text(size = FONT_AX, color = "black",
                               family = FONT_FAMILY),
      axis.title = element_text(size = FONT_AX, color = "black",
                                family = FONT_FAMILY),
      legend.title = element_text(size = FONT_LEGEND, family = FONT_FAMILY),
      legend.text = element_text(size = FONT_LEGEND, family = FONT_FAMILY),
      legend.key.height = unit(4.0, "mm"),
      legend.key.width = unit(3.0, "mm"),
      legend.position = "right",
      plot.background = element_rect(fill = "white", color = NA),
      panel.background = element_rect(fill = "white", color = NA),
      plot.margin = margin(3, 3, 3, 3, "mm")
    )
}

parse_bool <- function(x) {
  if (is.logical(x)) return(x)
  tolower(as.character(x)) %in% c("true", "t", "1", "yes")
}

metric_label <- function(metric) {
  label <- METRIC_GUIDE$label[match(metric, METRIC_GUIDE$metric)]
  ifelse(is.na(label), metric, label)
}

metric_limits <- function(metric) {
  cfg <- METRIC_GUIDE %>% filter(.data$metric == !!metric)
  if (nrow(cfg) == 1 && is.finite(cfg$lo) && is.finite(cfg$hi)) {
    return(c(cfg$lo, cfg$hi))
  }
  c(NA_real_, NA_real_)
}

safe_filename <- function(x) {
  gsub("[^A-Za-z0-9_]+", "_", x)
}

make_story_plot <- function(df, x_metric, y_metric, color_limits) {
  d <- df %>%
    filter(
      is.finite(.data[[x_metric]]),
      is.finite(.data[[y_metric]]),
      is.finite(cumulative_excess_shannon)
    )

  if (nrow(d) < 3) return(NULL)

  x_lim <- metric_limits(x_metric)
  y_lim <- metric_limits(y_metric)

  ggplot(d, aes(x = .data[[x_metric]], y = .data[[y_metric]])) +
    geom_point(
      aes(fill = cumulative_excess_shannon),
      shape = 21,
      color = "grey18",
      stroke = POINT_STROKE,
      size = POINT_SIZE,
      alpha = POINT_ALPHA
    ) +
    scale_fill_gradientn(
      colors = c(COLOR_LOW, COLOR_MID, COLOR_HIGH),
      limits = color_limits,
      oob = squish,
      name = "Cumulative -\nmean Shannon"
    ) +
    scale_x_continuous(
      limits = x_lim,
      breaks = pretty_breaks(4),
      labels = label_number(accuracy = 0.1),
      expand = expansion(mult = c(0, 0))
    ) +
    scale_y_continuous(
      limits = y_lim,
      breaks = pretty_breaks(4),
      labels = label_number(accuracy = 0.1),
      expand = expansion(mult = c(0, 0))
    ) +
    coord_cartesian(xlim = x_lim, ylim = y_lim, clip = "on") +
    labs(x = metric_label(x_metric), y = metric_label(y_metric)) +
    theme_story()
}

metrics_df <- read_csv(DATA_PATH, show_col_types = FALSE) %>%
  mutate(
    collapsed = parse_bool(collapsed),
    fluctuating_species_instability =
      parse_bool(fluctuating_species_instability)
  )

write_csv(
  METRIC_GUIDE,
  file.path(PROC_DIR, "mechanism_axes", "mechanism_story_metric_guide.csv")
)

for (scope in SCOPES_TO_PLOT) {
  for (win in WINDOWS_TO_PLOT) {
    d_base <- metrics_df %>%
      filter(window == !!win, collapsed == FALSE)

    if (scope == "fluctuating_only") {
      d_base <- d_base %>% filter(fluctuating_species_instability == TRUE)
    }

    if (nrow(d_base) == 0) next

    color_limits <- range(d_base$cumulative_excess_shannon, na.rm = TRUE)
    if (!all(is.finite(color_limits)) || color_limits[1] == color_limits[2]) {
      color_limits <- color_limits + c(-0.01, 0.01)
    }

    for (experiment in c("mortality", "temperature")) {
      d_exp <- d_base %>% filter(experiment == !!experiment)
      if (nrow(d_exp) == 0) next

      out_dir <- file.path(FIG_DIR, scope, win, experiment)
      dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

      for (i in seq_len(nrow(STORY_PAIRS))) {
        x_metric <- STORY_PAIRS$x[i]
        y_metric <- STORY_PAIRS$y[i]
        p <- make_story_plot(d_exp, x_metric, y_metric, color_limits)
        if (is.null(p)) next

        ggsave(
          file.path(out_dir, paste0(safe_filename(STORY_PAIRS$tag[i]), ".pdf")),
          p,
          width = W_PLOT,
          height = H_PLOT,
          units = "mm",
          device = cairo_pdf
        )
      }
    }
  }
}

cat("Done.\n")
cat(sprintf("Figures: %s\n", FIG_DIR))
cat("Story plots only; experiments separated; conditions not encoded.\n")
cat("Scopes: all_noncollapsed, fluctuating_only\n")
cat(sprintf("Windows: %s\n", paste(WINDOWS_TO_PLOT, collapse = ", ")))
